export const productColumns = [
  {
    prop: "PROD_MODE",
    label: "产品形态",
    selected: true,
    id: 1,
    align: "left",
    width: 120,
    columns: [
      { prop: "PROD_MODE1", label: "产品形态", selected: true },
      { prop: "PROD_MODE2", label: "产品形态", selected: true },
      {
        prop: "PROD_MODE3",
        label: "产品形态",
        selected: true,
        // columns: [
        //   { prop: "PROD_MODE11", label: "产品形态", selected: true },
        //   { prop: "PROD_MODE21", label: "产品形态", selected: true },
        //   { prop: "PROD_MODE31", label: "产品形态", selected: true },
        // ],
      },
    ],
  },
  {
    prop: "PROD_MODE2",
    label: "产品形态2",
    selected: true,
    id: 2,
    align: "left",
    width: 120,
    columns: [],
  },
  {
    prop: "PROD_MODE3",
    label: "产品形态3",
    selected: true,
    id: 3,
    align: "left",
    width: 120,
    columns: [],
  },
  {
    prop: "PROD_MODE4",
    label: "产品形态4",
    selected: true,
    id: 4,
    align: "left",
    width: 120,
    columns: [],
  },
  {
    prop: "PROD_MODE5",
    label: "产品形态5",
    selected: true,
    id: 5,
    align: "left",
    width: 120,
    columns: [],
  },
];
